name: Build project

on:
    workflow_call:
        inputs:
            ref:
                type: string
                required: false
                default: ""
            codeql:
                type: boolean
                required: false
                default: false
            dependency_graph:
                type: boolean
                required: false
                default: false
            upload_artifacts:
                type: boolean
                required: false
                default: false
        outputs:
            version:
                description: The project version
                value: ${{ jobs.build.outputs.version }}

jobs:
    build:
        outputs:
            version: ${{ steps.get-version.outputs.version }}
        runs-on: ubuntu-latest
        permissions:
            security-events: write
            contents: write
            packages: read
            actions: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                ref: ${{ inputs.ref }}

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                java-version: '21'
                distribution: 'temurin'
                cache: 'gradle'
                cache-dependency-path: |
                  **/*.gradle*
                  **/gradle-wrapper.properties
                  **/versions.properties
                  ./libs.versions.toml

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Make gradlew executable
              run: chmod +x ./gradlew

            - name: Initialize CodeQL
              if: inputs.codeql
              uses: github/codeql-action/init@v3
              with:
                languages: java-kotlin
                build-mode: manual

            - name: Get project version
              id: get-version
              run: echo "version=$(./gradlew -q --no-daemon printVersion)" > "$GITHUB_OUTPUT"

            - name: Build the project
              run: ./gradlew build --no-daemon
            
            - name: Perform CodeQL Analysis
              if: inputs.codeql
              uses: github/codeql-action/analyze@v3
              with:
                category: "/language:java-kotlin"
            
            - name: Generate and submit the dependency graph
              if: inputs.dependency_graph
              uses: gradle/actions/dependency-submission@v4
              with:
                additional-arguments: --no-daemon

            - name: Upload artifacts
              if: inputs.upload_artifacts
              uses: actions/upload-artifact@v4
              with:
                name: build-artifacts
                path: |
                  build/*-all.jar
                  !build/*-common-*.jar
