name: "Gradle Build"

on:
    push:
    pull_request:
    schedule:
        - cron: "0 0 * * 1"

jobs:
    build:
        uses: ./.github/workflows/build.yml
        with:
            codeql: true
            dependency_graph: true
            upload_artifacts: false
            ref: ${{ github.ref }}
        permissions:
            security-events: write
            contents: write
            packages: read
            actions: read
        secrets: inherit