name: "Publish"

on:
    push:
        branches: ["master"]
        tags: ["v*.*.*"]

jobs:
    build:
        uses: ./.github/workflows/build.yml
        with:
            codeql: false
            dependency_graph: false
            upload_artifacts: true
            ref: ${{ github.ref }}

    publish:
        runs-on: ubuntu-latest
        needs: build
        permissions:
            contents: write
        steps:
            - name: Download artifacts
              uses: dawidd6/action-download-artifact@v11
              with:
                workflow: build.yml
                name: build-artifacts
                path: build
            
            - name: Create release
              uses: softprops/action-gh-release@v2
              with:
                  name: ${{ github.ref_name }}
                  files: build/*.jar

