name: "Publish"

on:
    push:
        tags: ["v*.*.*"]

jobs:
    build:
        uses: ./.github/workflows/build.yml
        with:
            codeql: false
            dependency_graph: false
            upload_artifacts: true
            ref: ${{ github.ref }}
        permissions:
            security-events: write
            packages: read
            actions: read
            contents: read

    publish:
        runs-on: ubuntu-latest
        needs: build
        permissions:
            contents: write
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                name: build-artifacts
                path: build
            
            - name: Rename artifacts
              run: find . -type f -name "*-all.jar" -exec bash -c 'f=$(basename $0); dir=$(dirname $0); mv "$0" "${dir}/${f/-all/}"' {} \;

            - name: Create release
              uses: softprops/action-gh-release@v2
              with:
                  name: ${{ github.ref_name }}
                  files: build/*.jar

